# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbK43MRzKLzvy3aJxF9pabr9rujW_zW4
"""

!pip install dagshub
!pip install lightgbm
!pip install mlflow

import dagshub
import mlflow
import pandas as pd
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score

# Set up DagsHub for MLflow tracking
dagshub.init(
    repo_owner="rifzkiadiyaksa", repo_name="SMSML_Rifzki", mlflow=True
)
mlflow.set_experiment("Cars_Seles")

# Enable MLflow autologging for LightGBM
mlflow.lightgbm.autolog()

# Load data
train_df = pd.read_csv("/content/train_data.csv")
test_df = pd.read_csv("/content/test_data.csv")

X_train = train_df.drop(columns="annual_income_category")
y_train = train_df["annual_income_category"]
X_test = test_df.drop(columns="annual_income_category")
y_test = test_df["annual_income_category"]

# Train a basic LightGBM model
with mlflow.start_run(run_name="LightGBM_Baseline"):
    model = LGBMClassifier(random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    # Log test accuracy
    preds = model.predict(X_test)
    test_accuracy = accuracy_score(y_test, preds)
    mlflow.log_metric("test_accuracy", test_accuracy)